export enum StringValues {
  loading = "Loading",
  noDataAvailable = "No data available",
  login = "Login",
  email = "Email",
  password = "Password",
  confirmPassword = "Confirm your password",
  newAccount = "New account",
  firstName = "First name",
  lastName = "Last name",
  inputEmailAndPassword = "Please input your email and password",
  inputDetails = "Please input all your details",
  passwordsNoMatch = "The passwords don't match",
  register = "Register",
  createAccount = "New? Create account",
  alreadyHaveAccount = "Already have an account? Login",
  contact = "Contact",
  logout = "Logout",
  appVersion = "App version",
  uuid = "UUID",
  termsAndConditions = "Terms & Conditions",
  yourDetails = "Your details",
}
